# Generated by Django 3.1.6 on 2021-03-13 03:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('airbnb', models.DecimalField(decimal_places=2, max_digits=4)),
                ('airline', models.DecimalField(decimal_places=2, max_digits=4)),
                ('amazon', models.DecimalField(decimal_places=2, max_digits=4)),
                ('automotive', models.DecimalField(decimal_places=2, max_digits=4)),
                ('best_buy', models.DecimalField(decimal_places=2, max_digits=4)),
                ('car_rental', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cruise', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cvs', models.DecimalField(decimal_places=2, max_digits=4)),
                ('department_store', models.DecimalField(decimal_places=2, max_digits=4)),
                ('drugstore', models.DecimalField(decimal_places=2, max_digits=4)),
                ('food_delivery', models.DecimalField(decimal_places=2, max_digits=4)),
                ('food_restaurant', models.DecimalField(decimal_places=2, max_digits=4)),
                ('furnishings', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('grocery_store', models.DecimalField(decimal_places=2, max_digits=4)),
                ('health_fitness', models.DecimalField(decimal_places=2, max_digits=4)),
                ('home_improvement', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hotel', models.DecimalField(decimal_places=2, max_digits=4)),
                ('internet_cable_phone', models.DecimalField(decimal_places=2, max_digits=4)),
                ('liquor_store', models.DecimalField(decimal_places=2, max_digits=4)),
                ('movie_theather', models.DecimalField(decimal_places=2, max_digits=4)),
                ('office_supply_store', models.DecimalField(decimal_places=2, max_digits=4)),
                ('other', models.DecimalField(decimal_places=2, max_digits=4)),
                ('parking', models.DecimalField(decimal_places=2, max_digits=4)),
                ('paypal', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rideshare_lyft', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rideshare_other', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rideshare_uber', models.DecimalField(decimal_places=2, max_digits=4)),
                ('streaming_service', models.DecimalField(decimal_places=2, max_digits=4)),
                ('target', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tourist_attraction', models.DecimalField(decimal_places=2, max_digits=4)),
                ('travel_other', models.DecimalField(decimal_places=2, max_digits=4)),
                ('travel_agency', models.DecimalField(decimal_places=2, max_digits=4)),
                ('utilities', models.DecimalField(decimal_places=2, max_digits=4)),
                ('walgreens', models.DecimalField(decimal_places=2, max_digits=4)),
                ('walmart', models.DecimalField(decimal_places=2, max_digits=4)),
                ('wholesale_club', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardCurrency',
            fields=[
                ('currency_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('value_percent', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='SignUpBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spend_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('duration_days', models.DecimalField(decimal_places=2, max_digits=9)),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.creditcardtype')),
            ],
        ),
        migrations.CreateModel(
            name='UserCreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('expiration', models.CharField(max_length=5)),
                ('security_code', models.CharField(max_length=5)),
                ('open_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('reward_value_override', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('card_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.creditcardtype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('welcome_offer', models.ForeignKey(blank=True, limit_choices_to={'card_type': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.creditcardtype')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.signupbonus')),
            ],
        ),
        migrations.AddField(
            model_name='creditcardtype',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.issuer'),
        ),
        migrations.AddField(
            model_name='creditcardtype',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.network'),
        ),
        migrations.AddField(
            model_name='creditcardtype',
            name='reward_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rewardcurrency'),
        ),
    ]
