# Generated by Django 3.1.6 on 2021-04-19 14:35

import api.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210419_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='key',
            field=api.custom_fields.EncryptedField(max_length=512),
        ),
    ]
