# Generated by Django 3.1.6 on 2021-04-19 14:40

import api.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210419_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreditcard',
            name='card_number',
            field=api.custom_fields.EncryptedField(max_length=512),
        ),
        migrations.AlterField(
            model_name='usercreditcard',
            name='expiration',
            field=api.custom_fields.EncryptedField(max_length=512),
        ),
        migrations.AlterField(
            model_name='usercreditcard',
            name='security_code',
            field=api.custom_fields.EncryptedField(max_length=512),
        ),
    ]
